products = [
    {
        "_id": 1,
        "name": "Capri",
        "image": "/images/capri.jpg",
        "brand": "Kaczmarek",
        "category": "Cobblestone",
        "description": "Klasyczny wygląd, równe, regularne kształty przypominające rytm antycznych nawierzchni, przywołują skojarzenia ze śródziemnomorskim klimatem. W kolorze barwy jesieni nawierzchnia wizualnie ociepla otoczenie nie pozbawiając rezydencji dostojnego wyglądu.",
        "rating": None,
        "numReviews": 0,
        "price": "89.99",
        "countInStock": 10,
        "createdAt": "2022-03-10T03:24:33.219840Z",
        "user": 1
    },
    {
        "_id": 2,
        "name": "Dilos",
        "image": "/images/dilos.jpg",
        "brand": "Kaczmarek",
        "category": "Cobblestone",
        "description": "Klasyczny wygląd, równe, regularne kształty przypominające rytm antycznych nawierzchni, przywołują skojarzenia ze śródziemnomorskim klimatem. W kolorze barwy jesieni nawierzchnia wizualnie ociepla otoczenie nie pozbawiając rezydencji dostojnego wyglądu.",
        "rating": None,
        "numReviews": 0,
        "price": "599.99",
        "countInStock": 0,
        "createdAt": "2022-03-10T03:34:11.971298Z",
        "user": 1
    },
    {
        "_id": 3,
        "name": "Elba",
        "image": "/images/elba.jpg",
        "brand": "Kaczmarek",
        "category": "Cobblestone",
        "description": "Klasyczny wygląd, równe, regularne kształty przypominające rytm antycznych nawierzchni, przywołują skojarzenia ze śródziemnomorskim klimatem. W kolorze barwy jesieni nawierzchnia wizualnie ociepla otoczenie nie pozbawiając rezydencji dostojnego wyglądu.",
        "rating": None,
        "numReviews": 0,
        "price": "929.99",
        "countInStock": 5,
        "createdAt": "2022-03-10T03:34:39.807006Z",
        "user": 1
    },
    {
        "_id": 4,
        "name": "Płyta Corso",
        "image": "/images/plyta_corso.jpg",
        "brand": "Kaczmarek",
        "category": "Cobblestone",
        "description": "Klasyczny wygląd, równe, regularne kształty przypominające rytm antycznych nawierzchni, przywołują skojarzenia ze śródziemnomorskim klimatem. W kolorze barwy jesieni nawierzchnia wizualnie ociepla otoczenie nie pozbawiając rezydencji dostojnego wyglądu.",
        "rating": None,
        "numReviews": 0,
        "price": "399.99",
        "countInStock": 11,
        "createdAt": "2022-03-10T03:35:14.875449Z",
        "user": 1
    },
    {
        "_id": 5,
        "name": "Rodos",
        "image": "/images/rodos.jpg",
        "brand": "Kaczmarek",
        "category": "Cobblestone",
        "description": "Klasyczny wygląd, równe, regularne kształty przypominające rytm antycznych nawierzchni, przywołują skojarzenia ze śródziemnomorskim klimatem. W kolorze barwy jesieni nawierzchnia wizualnie ociepla otoczenie nie pozbawiając rezydencji dostojnego wyglądu.",
        "rating": None,
        "numReviews": 0,
        "price": "49.99",
        "countInStock": 7,
        "createdAt": "2022-03-10T03:35:42.913240Z",
        "user": 1
    },
    {
        "_id": 6,
        "name": "Via Grande",
        "image": "/images/via_grande.jpg",
        "brand": "Kaczmarek",
        "category": "Cobblestone",
        "description": "Klasyczny wygląd, równe, regularne kształty przypominające rytm antycznych nawierzchni, przywołują skojarzenia ze śródziemnomorskim klimatem. W kolorze barwy jesieni nawierzchnia wizualnie ociepla otoczenie nie pozbawiając rezydencji dostojnego wyglądu.",
        "rating": None,
        "numReviews": 0,
        "price": "29.99",
        "countInStock": 0,
        "createdAt": "2022-03-10T03:36:31.961765Z",
        "user": 1
    },
    {
        "_id": 7,
        "name": "Via Romano",
        "image": "/images/via_romano.jpg",
        "brand": "Kaczmarek",
        "category": "Cobblestone",
        "description": "Klasyczny wygląd, równe, regularne kształty przypominające rytm antycznych nawierzchni, przywołują skojarzenia ze śródziemnomorskim klimatem. W kolorze barwy jesieni nawierzchnia wizualnie ociepla otoczenie nie pozbawiając rezydencji dostojnego wyglądu.",
        "rating": None,
        "numReviews": 0,
        "price": "29.99",
        "countInStock": 34,
        "createdAt": "2022-03-10T03:37:05.641631Z",
        "user": 1
    }
]